[package]
name = "kairo_circuit_breaker"
version = "0.1.0"
edition = "2023_11"

[dependencies]
sncast_std = "0.48.1"
snforge_std = "0.48.1"
starknet = ">=2.3.0"

[tool.snforge]
# Starknet Foundry configuration
exit_first = true

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
build = "scarb build"
test = "snforge test"
format = "scarb fmt"
